#pragma config(Motor,  port2,           driveL,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           driveR,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           slider,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           clawL,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           clawR,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int leftX = 0;
int leftY = 0;
int rightY = 0;
int rightX = 0;
const bool on = true;
int thresh = 12;

task drive()
{
	while(on)
	{
		motor[driveL] = leftX - leftY;
		motor[driveR] = -leftX + leftY;
	}
}

task manipulator()
{

	motor [clawL] = 20;
	motor [clawR] = -20;

	while(on)
	{

		motor[slider] = rightY;

		if(vexRT[Btn8L])
		{
			motor[clawL] = -60;
			motor[clawR] = 60;
		}

		if(vexRT[Btn8R])
		{
			motor[clawL] = 20;

			motor[clawR] = -20;
		}
	}
}

task main()
{
	startTask(drive);
	startTask(manipulator);

	while(on)
	{
		rightX = vexRT(Ch1);
		if(abs(rightX)<thresh){
			rightX = 0;
		}
		rightY = vexRT(Ch2);
		if(abs(rightY)<thresh){
			rightY = 0;
		}
		leftY = vexRT(Ch3);
		if(abs(leftY)<thresh){
			leftY = 0;
		}
		leftX = vexRT(Ch4);
		if(abs(leftX)<thresh){
			leftX = 0;
		}
	}
}
